language: haskell
ghc:
  - 7.8

script:
  - cabal configure && cabal build

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxxf86vm-dev libopenal-dev
  - wget https://github.com/Mokosha/netwire-input/archive/master.zip -O /tmp/netwire-input.zip
  - unzip /tmp/netwire-input.zip
  - wget https://github.com/Mokosha/netwire-input-glfw/archive/master.zip -O /tmp/netwire-input-glfw.zip
  - unzip /tmp/netwire-input-glfw.zip

install:
  - cabal install netwire-input-master/
  - cabal install netwire-input-glfw-master/
  - cabal install --only-dependencies
