flags:
  lambency:
    examples: true
# build:
#   library-profiling: true
#   executable-profiling: true
packages:
- .
- location:
    git: http://www.github.com/Mokosha/netwire-input-glfw.git
    commit: 0f04a165c88087615ba5aa66ce90f9138e9fc7f7
  extra-dep: true
extra-deps:
- GLFW-b-3.2.1.0
- bindings-GLFW-3.2.1.1
resolver: lts-11.6
