# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: ghc-7.10.2

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- GLFW-b-1.4.7.3
- GLURaw-2.0.0.1
- HCodecs-0.5
- JuicyPixels-3.2.7
- ObjectName-1.1.0.1
- OpenAL-1.7.0.3
- OpenGL-3.0.0.1
- OpenGLRaw-3.1.0.0
- QuickCheck-2.8.2
- StateVar-1.1.0.3
- adjunctions-4.2.2
- base-orphans-0.5.3
- bifunctors-4.2.1
- bindings-DSL-1.0.23
- bindings-GLFW-3.1.1.4
- bytes-0.15.2
- cereal-0.5.1.0
- comonad-4.2.7.2
- contravariant-1.4
- distributive-0.4.4
- exceptions-0.8.2.1
- fixed-0.2.1.1
- free-4.12.4
- freetype2-0.1.1
- half-0.2.2.3
- hashable-1.2.4.0
- kan-extensions-4.2.3
- lens-4.9.1
- linear-1.20.4
- mtl-2.2.1
- netwire-5.0.1
- netwire-input-0.0.4
- netwire-input-glfw-0.0.4
- parallel-3.2.1.0
- parsec-3.1.9
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-4.4.1
- random-1.1
- reflection-1.5.2.1
- scientific-0.3.4.6
- semigroupoids-4.3
- semigroups-0.18.1
- stm-2.4.4.1
- tagged-0.8.3
- text-1.2.2.1
- tf-random-0.5
- transformers-compat-0.4.0.4
- unordered-containers-0.2.7.0
- vector-0.10.12.3
- void-0.7.1
- zlib-0.6.1.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
