flags: {}
user-message: ! 'Warning: Specified resolver could not satisfy all dependencies. Some
  external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- '.'
extra-deps:
- OpenAL-1.7.0.3
- freetype2-0.1.1
- netwire-5.0.0
- netwire-input-0.0.4
- netwire-input-glfw-0.0.4
- text-1.2.2.1
resolver: lts-5.9
